name: Deploy Resources

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform -chdir=./tf init

    - name: Terraform Apply
      run: terraform -chdir=./tf apply -auto-approve

    - name: Store Outputs as Secrets
      run: |
        gh secret set RESOURCE_GROUP --body "$(terraform output -raw resource_group_name)"
        gh secret set VNET_NAME --body "$(terraform output -raw virtual_network_name)"
        gh secret set SUBNET_NAME --body "$(terraform output -raw subnet_name)"
        gh secret set ACR_NAME --body "$(terraform output -raw container_registry_name)"
        gh secret set AKS_NAME --body "$(terraform output -raw aks_cluster_name)"
  
    - name: Enable Routing Add-on with NGINX
      run: |
        az aks approuting enable --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_NAME }}
    
    - name: Set up kubectl for AKS
      run: |
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_NAME }}

    - name: Run kubectl command
      run: |
        kubectl get pods --namespace default