name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform -chdir=./tf init \
          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
          -backend-config="key="terraform.tfstate"" \
          -backend-config="access_key=${{ secrets.ACCESS_KEY }}"

    - name: Terraform Plan -destroy
      run: terraform plan -destroy -out=tfplan

    - name: Terraform Apply -destroy
      run: terraform apply -destroy -auto-approve tfplan