name: Destroy Resources

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Environment Variables from Secrets
      run: |
        RESOURCE_GROUP=${{ secrets.RESOURCE_GROUP }}
        VNET_NAME=${{ secrets.VNET_NAME }}
        SUBNET_NAME=${{ secrets.SUBNET_NAME }}
        ACR_NAME=${{ secrets.ACR_NAME }}
        AKS_NAME=${{ secrets.AKS_NAME }}
        echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_ENV
        echo "VNET_NAME=$VNET_NAME" >> $GITHUB_ENV
        echo "SUBNET_NAME=$SUBNET_NAME" >> $GITHUB_ENV
        echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
        echo "AKS_NAME=$AKS_NAME" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform -chdir=./tf init

    - name: Terraform Destroy
      run: terraform -chdir=./tf destroy -auto-approve
